-- Run this in your Supabase SQL Editor to create the missing tables and STORAGE BUCKETS

-- 1. Create SONGS table (for Music section)
create table if not exists songs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  song_url text, -- Matches the actual column name found
  filename text
);

-- 2. Create CONTENT table (for Hero/About text updates)
create table if not exists content (
  key text primary key,
  value text,
  last_updated timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create PICTURES table (Missing)
create table if not exists pictures (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  url text,
  filename text
);

-- 4. Create VIDEOS table (if not exists)
create table if not exists videos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  video_url text,
  video_type text,
  embed_url text
);


-- 5. Enable RLS
alter table songs enable row level security;
alter table content enable row level security;
alter table pictures enable row level security;
alter table videos enable row level security;

-- 6. Create Policies
create policy "Public Read Songs" on songs for select using (true);
create policy "Public Read Content" on content for select using (true);
create policy "Public Read Pictures" on pictures for select using (true);
create policy "Public Read Videos" on videos for select using (true);

create policy "Allow Insert Songs" on songs for insert with check (true);
create policy "Allow Update Content" on content for update using (true);
create policy "Allow Insert Content" on content for insert with check (true);
create policy "Allow Insert Pictures" on pictures for insert with check (true);
create policy "Allow Insert Videos" on videos for insert with check (true);


-- 7. STORAGE BUCKET CREATION (Critical for Uploads)
-- This requires the 'storage' extension which is default enabled
insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do nothing;

-- 8. Storage Policies (Allow public read, allow insert)
create policy "Public Access Media" on storage.objects for select
using ( bucket_id = 'media' );

create policy "Anon Upload Media" on storage.objects for insert
with check ( bucket_id = 'media' );

create policy "Public Access Images" on storage.objects for select
using ( bucket_id = 'images' );

create policy "Anon Upload Images" on storage.objects for insert
with check ( bucket_id = 'images' );
