-- Run this in your Supabase SQL Editor to create the missing tables

-- 1. Create SONGS table (for Music section)
create table if not exists songs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  url text, -- The file URL
  filename text
);

-- 2. Create CONTENT table (for Hero/About text updates)
create table if not exists content (
  key text primary key,
  value text,
  last_updated timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable RLS (Optional but recommended)
alter table songs enable row level security;
alter table content enable row level security;

-- 4. Create Policies (Allow public read, allow insert/update for anon/authenticated)
-- Note: 'anon' key is used by the client for now.
create policy "Public Read Songs" on songs for select using (true);
create policy "Public Read Content" on content for select using (true);

create policy "Allow Insert Songs" on songs for insert with check (true);
create policy "Allow Update Content" on content for update using (true);
create policy "Allow Insert Content" on content for insert with check (true);

-- 5. Fix VIDEOS table if needed (Ensure public read)
-- (Assuming table exists, just ensuring policy)
alter table videos enable row level security;
create policy "Public Read Videos" on videos for select using (true);
create policy "Allow Insert Videos" on videos for insert with check (true);
