-- Run this in your Supabase SQL Editor to create the missing tables

-- 1. Create SONGS table (for Music section)
-- Note: In your current DB, 'url' might be named 'song_url'.
create table if not exists songs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  song_url text, -- Matches the actual column name found
  filename text
);

-- 2. Create CONTENT table (for Hero/About text updates)
create table if not exists content (
  key text primary key,
  value text,
  last_updated timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create PICTURES table (Missing)
create table if not exists pictures (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  url text,
  filename text
);

-- 4. Enable RLS
alter table songs enable row level security;
alter table content enable row level security;
alter table pictures enable row level security;

-- 5. Create Policies
create policy "Public Read Songs" on songs for select using (true);
create policy "Public Read Content" on content for select using (true);
create policy "Public Read Pictures" on pictures for select using (true);

create policy "Allow Insert Songs" on songs for insert with check (true);
create policy "Allow Update Content" on content for update using (true);
create policy "Allow Insert Content" on content for insert with check (true);
create policy "Allow Insert Pictures" on pictures for insert with check (true);
create policy "Allow Delete Pictures" on pictures for delete using (true);

-- 6. Fix VIDEOS table if needed
alter table videos enable row level security;
create policy "Public Read Videos" on videos for select using (true);
create policy "Allow Insert Videos" on videos for insert with check (true);
